// <auto-generated />
namespace SpadCompanyPanel.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init));
        
        string IMigrationMetadata.Id
        {
<<<<<<< HEAD:SazeNegar.Infrastructure/Migrations/202107070904401_init.Designer.cs
            get { return "202107070904401_init"; }
=======
            get { return "202107060614549_init"; }
>>>>>>> master:SazeNegar.Infrastructure/Migrations/202107060614549_init.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
